# Setup
title:               PyC
tagline:             'Python Cheatbook'
description:         'Python Commands'
url:                 https://rajasgs.github.io/pyc/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Raja CSP Raman
  url:               https://linktr.ee/rajacsp

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
